name: "Publish"

on:
  workflow_dispatch: # Manual trigger
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Set up Java"
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17
      - name: "Set up Gradle"
        uses: gradle/actions/setup-gradle@v4
      - name: "Gradle Build and Test"
        run: ./gradlew check build publish publishPlugins --stacktrace
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.SIGNING_PGP_KEY_ID }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_PGP_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PGP_PASSWORD }}
      - name: "Upload artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: ./build/libs/
