name: "Test"

on:
  push:
    branches:
      - "**"
  pull_request:

concurrency: build-${{ github.sha }}

jobs:
  build:
    strategy:
      matrix:
        java: [17, 21]
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Set up Java"
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}
      - name: "Set up Gradle"
        uses: gradle/actions/setup-gradle@v4
      - name: "Gradle Build and Test"
        run: ./gradlew build check --stacktrace --parallel
      - name: "Upload artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts_j${{ matrix.java }}
          path: ./build/libs/
      - name: "Upload test reports"
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: test_reports_j${{ matrix.java }}
          retention-days: 2
          path: ./build/reports/tests/
